// Code generated from epubcheck v5.4.0 (MessageId.java, DefaultSeverities.java
// and MessageBundle.properties); DO NOT EDIT. epubcheck is distributed under
// the BSD 3-Clause License; see THIRD_PARTY_NOTICES.md.

package check

// catalogue maps each epubcheck message ID to its default severity and its
// English text, a format string with %1$s-style arguments.
var catalogue = map[string]struct {
	Severity Severity
	Text     string
}{
	"ACC-001":  {Suppressed, ""},
	"ACC-002":  {Suppressed, ""},
	"ACC-003":  {Suppressed, ""},
	"ACC-004":  {Suppressed, "Html \"a\" element must have text."},
	"ACC-005":  {Suppressed, "Table heading cells should be identified by \"th\" elements for accessibility."},
	"ACC-006":  {Suppressed, "Tables should include a \"thead\" element for accessibility."},
	"ACC-007":  {Suppressed, "Content Documents do not use \"epub:type\" attributes for semantic inflection."},
	"ACC-008":  {Suppressed, ""},
	"ACC-009":  {Usage, "MathML should either have an \"alttext\" attribute or \"annotation-xml\" child element."},
	"ACC-010":  {Suppressed, ""},
	"ACC-011":  {Usage, "SVG hyperlink has no accessible name"},
	"ACC-012":  {Suppressed, "Table elements should include a caption element."},
	"ACC-013":  {Suppressed, ""},
	"ACC-014":  {Suppressed, ""},
	"ACC-015":  {Suppressed, ""},
	"ACC-016":  {Suppressed, ""},
	"ACC-017":  {Suppressed, ""},
	"CHK-001":  {Error, "The custom message overrides file was not found."},
	"CHK-002":  {Error, "Unrecognized custom message id %1$s encountered in message overrides file \"%2$s\"."},
	"CHK-003":  {Error, "Unrecognized custom message severity \"%1$s\" encountered in message overrides file \"%2$s\"."},
	"CHK-004":  {Error, "The custom message contains too many parameters in message overrides file \"%1$s\"."},
	"CHK-005":  {Error, "The custom suggestion contains too many parameters in message overrides file \"%1$s\"."},
	"CHK-006":  {Error, "Unable to parse the custom format parameter in message overrides file \"%1$s\"."},
	"CHK-007":  {Error, "Error encountered while processing custom message file \"%1$s\": \"%2$s\"."},
	"CHK-008":  {Error, "Error encountered while processing an item \"%1$s\"; skip other checks for the item."},
	"CSS-001":  {Error, "The \"%1$s\" property must not be included in an EPUB Style Sheet."},
	"CSS-002":  {Error, "Empty or NULL reference found."},
	"CSS-003":  {Warning, "CSS document is encoded in UTF-16. It should be encoded in UTF-8 instead."},
	"CSS-004":  {Error, "CSS documents must be encoded in UTF-8, detected %1$s;"},
	"CSS-005":  {Usage, "Conflicting alternate style tags found: %1$s."},
	"CSS-006":  {Usage, "CSS selector specifies fixed position."},
	"CSS-007":  {Info, "Font-face reference \"%1$s\" refers to non-standard font type \"%2$s\"."},
	"CSS-008":  {Error, "An error occurred while parsing the CSS: %1$s."},
	"CSS-009":  {Suppressed, ""},
	"CSS-010":  {Suppressed, ""},
	"CSS-011":  {Suppressed, ""},
	"CSS-012":  {Suppressed, ""},
	"CSS-013":  {Suppressed, ""},
	"CSS-015":  {Error, "Alternative style sheets must have a title."},
	"CSS-016":  {Suppressed, ""},
	"CSS-017":  {Suppressed, ""},
	"CSS-019":  {Warning, "CSS font-face declaration has no attributes."},
	"CSS-020":  {Suppressed, ""},
	"CSS-021":  {Suppressed, ""},
	"CSS-022":  {Suppressed, ""},
	"CSS-023":  {Suppressed, ""},
	"CSS-024":  {Suppressed, ""},
	"CSS-025":  {Suppressed, ""},
	"CSS-028":  {Usage, "Use of Font-face declaration."},
	"CSS-029":  {Usage, "Found CSS class name \"%1$s\" but no \"%2$s\" property was declared in the package document."},
	"CSS-030":  {Error, "The package document declares media overlays styling class names but no CSS was found in the content document."},
	"HTM-001":  {Error, "Any publication resource that is an XML-based media type must be a valid XML 1.0 document. XML version found: %1$s."},
	"HTM-002":  {Warning, "The installed xml parser doesn’t support xml version verification. Xml files must be a valid XML 1.0 document."},
	"HTM-003":  {Error, "External entities are not allowed in EPUB v3 documents. External entity declaration found: %1$s."},
	"HTM-004":  {Error, "Irregular DOCTYPE: found \"%1$s\", expected \"%2$s\"."},
	"HTM-005":  {Usage, "An external reference was found."},
	"HTM-006":  {Suppressed, ""},
	"HTM-007":  {Warning, "Empty or whitespace-only value of attribute ssml:ph."},
	"HTM-008":  {Suppressed, ""},
	"HTM-009":  {Error, "The DOCTYPE provided is obsolete or irregular and can be removed."},
	"HTM-010":  {Usage, "Namespace \"%1$s\" is unusual for the prefix \"epub\"."},
	"HTM-011":  {Error, "Entity is undeclared."},
	"HTM-012":  {Suppressed, ""},
	"HTM-013":  {Suppressed, ""},
	"HTM-014":  {Suppressed, ""},
	"HTM-014a": {Suppressed, ""},
	"HTM-015":  {Suppressed, ""},
	"HTM-016":  {Suppressed, ""},
	"HTM-017":  {Suppressed, ""},
	"HTM-018":  {Suppressed, ""},
	"HTM-019":  {Suppressed, ""},
	"HTM-020":  {Suppressed, ""},
	"HTM-021":  {Suppressed, ""},
	"HTM-022":  {Suppressed, ""},
	"HTM-023":  {Suppressed, ""},
	"HTM-024":  {Suppressed, ""},
	"HTM-025":  {Warning, "Non-registered URI scheme type found in href."},
	"HTM-027":  {Suppressed, ""},
	"HTM-028":  {Suppressed, ""},
	"HTM-029":  {Suppressed, ""},
	"HTM-033":  {Suppressed, ""},
	"HTM-036":  {Suppressed, ""},
	"HTM-038":  {Suppressed, ""},
	"HTM-044":  {Usage, "Namespace uri \"%1$s\" was included but not used."},
	"HTM-045":  {Usage, "Encountered empty href."},
	"HTM-046":  {Error, "Fixed layout document has no \"viewport\" meta element."},
	"HTM-047":  {Error, "Viewport metadata \"%1$s\" has a syntax error"},
	"HTM-048":  {Error, "SVG Fixed-Layout Documents must have a \"viewBox\" attribute (on the outermost \"svg\" element)."},
	"HTM-049":  {Suppressed, ""},
	"HTM-050":  {Suppressed, ""},
	"HTM-051":  {Warning, "Found Microdata semantic enrichments but no RDFa. EDUPUB recommends using RDFa Lite."},
	"HTM-052":  {Error, "The property \"region-based\" is only allowed on nav elements in Data Navigation Documents."},
	"HTM_053":  {Suppressed, ""},
	"HTM_054":  {Error, "Custom attribute namespace (\"%1$s\") must not include the string \"%2$s\" in its domain."},
	"HTM_055":  {Usage, "The \"%1$s\" element should not be used (discouraged construct)"},
	"HTM_056":  {Error, "Viewport metadata has no \"%1$s\" dimension (both \"width\" and \"height\" properties are required)"},
	"HTM_057":  {Error, "Viewport \"%1$s\" value must be a positive number or the keyword \"device-%1$s\""},
	"HTM_058":  {Error, "HTML documents must be encoded in UTF-8, but UTF-16 was detected."},
	"HTM_059":  {Error, "Viewport \"%1$s\" property must not be defined more than once, but found values [%2$s]."},
	"HTM_060a": {Usage, "EPUB reading systems must ignore secondary viewport meta elements in fixed-layout documents; viewport declaration \"%1$s\" will be ignored. "},
	"HTM_060b": {Usage, "EPUB reading systems must ignore viewport meta elements in reflowable documents; viewport declaration \"%1$s\" will be ignored."},
	"HTM_061":  {Error, "\"%1$s\" is not a valid custom data attribute (it must have at least one character after the hyphen, be XML-compatible, and not contain ASCII uppercase letters)."},
	"HTM_062":  {Usage, "SVG \"xlink:href\" attribute is deprecated; an \"href\" attribute should be used instead."},
	"HTM_063":  {Usage, "SVG \"xlink:href\" attribute value (\"%1$s\") should be equal to the \"href\" attribute value (\"%2$s\")."},
	"INF-001":  {Info, "Rule %1$s is under review and its severity may change in a future release. See the discussion at %2$s"},
	"MED-001":  {Suppressed, ""},
	"MED-002":  {Suppressed, ""},
	"MED-003":  {Error, "Picture \"img\" elements must reference core media type resources, but found resource \"%1$s\" of type \"%2$s\"."},
	"MED-004":  {Error, "Image file header may be corrupted."},
	"MED-005":  {Error, "Media Overlay audio reference %1$s to non-standard audio type %2$s found."},
	"MED-008":  {Error, "The time specified in the clipBegin attribute must not be after clipEnd."},
	"MED-009":  {Error, "The time specified in the clipBegin attribute must not be the same as clipEnd."},
	"MED_006":  {Suppressed, ""},
	"MED_007":  {Error, "Picture \"source\" elements must define a \"type\" attribute when they reference foreign resources; found resource \"%1$s\" of type \"%2$s\"."},
	"MED_010":  {Error, "EPUB Content Documents referenced from a Media Overlay must specify the \"media-overlay\" attribute."},
	"MED_011":  {Error, "EPUB Content Document referenced from multiple Media Overlay Documents."},
	"MED_012":  {Error, "The \"media-overlay\" attribute does not match the ID of the Media Overlay that refers to this document."},
	"MED_013":  {Error, "Media Overlay Document referenced from the \"media-overlay\" attribute does not contain a reference to this Content Document."},
	"MED_014":  {Error, "Media overlay audio file URLs must not have a fragment, but found '#%1$s'. "},
	"MED_015":  {Usage, "Media overlay text references must be in reading order. Text target \"%1$s\" is before the previous link target in %2$s order."},
	"MED_016":  {Warning, "Media Overlays total duration should be the sum of the durations of all Media Overlays documents."},
	"MED_017":  {Warning, "URL fragment should indicate an element ID, but found '#%1$s'."},
	"MED_018":  {Warning, "URL fragment should be an SVG fragment identifier, but found '#%1$s'."},
	"NAV-001":  {Error, "The nav file is not supported for EPUB v2."},
	"NAV-002":  {Suppressed, ""},
	"NAV-003":  {Error, "The Navigation Document must have a page list when content document(s) contain page breaks (epub:type=\"pagebreak\")."},
	"NAV-004":  {Usage, "The Navigation Document should contain the full document heading hierarchy in EDUPUB."},
	"NAV-005":  {Usage, "Content documents contain \"audio\" elements but the Navigation Document does not have a listing of audio clips (epub:type=\"loa\")."},
	"NAV-006":  {Usage, "Content documents contain \"figure\" elements but the Navigation Document does not have a listing of figures (epub:type=\"loi\")."},
	"NAV-007":  {Usage, "Content documents contain \"table\" elements but the Navigation Document does not have a listing of tables (epub:type=\"lot\")."},
	"NAV-008":  {Usage, "Content documents contain \"video\" elements but the Navigation Document does not have a listing of video clips (epub:type=\"lov\")."},
	"NAV-009":  {Error, "Region-based navigation links must point to Fixed-Layout Documents."},
	"NAV-010":  {Error, "\"%1$s\" nav must not link to remote resources; found link to \"%2$s\"."},
	"NAV-011":  {Warning, "\"%1$s\" nav must be in reading order; link target \"%2$s\" is before the previous link’s target in %3$s order."},
	"NCX-001":  {Error, "NCX identifier (\"%1$s\") does not match OPF identifier (\"%2$s\")."},
	"NCX-002":  {Suppressed, ""},
	"NCX-003":  {Suppressed, ""},
	"NCX-004":  {Usage, "NCX identifier (\"dtb:uid\" metadata) should not contain leading or trailing whitespace."},
	"NCX-005":  {Suppressed, ""},
	"NCX-006":  {Usage, "Empty \"text\" label in the NCX document"},
	"OBS-001":  {Usage, "Usage of %1$s is outdated."},
	"OPF-001":  {Error, "There was an error when parsing the EPUB version: %1$s."},
	"OPF-002":  {Fatal, "The OPF file \"%1$s\" was not found in the EPUB."},
	"OPF-003":  {Usage, "Item \"%1$s\" exists in the EPUB, but is not declared in the OPF manifest."},
	"OPF-004":  {Warning, "Invalid prefix declaration: leading or trailing whitespace is not allowed."},
	"OPF-004a": {Error, "Invalid prefix declaration: found empty prefix."},
	"OPF-004b": {Error, "Invalid prefix \"%1$s\": must be a valid non-colonized name (aka \"NCName\")."},
	"OPF-004c": {Error, "Invalid prefix declaration: prefix \"%1$s\" must be immediately followed by a colon character (\":\")."},
	"OPF-004d": {Error, "Invalid prefix declaration: prefix \"%1$s\" must be separated by its URI with a space."},
	"OPF-004e": {Warning, "Invalid prefix declaration: found illegal whitespace between prefix and URI."},
	"OPF-004f": {Warning, "Invalid prefix declaration: found illegal whitespace between prefix mappings."},
	"OPF-005":  {Error, "Invalid prefix declaration: URI for prefix \"%1$s\" doesn’t exist."},
	"OPF-006":  {Error, "Invalid prefix declaration: URI \"%1$s\" is not a valid URI."},
	"OPF-007":  {Warning, "Re-declaration of reserved prefix \"%1$s\"."},
	"OPF-007a": {Error, "Invalid prefix mapping: prefix \"_\" must not be declared."},
	"OPF-007b": {Error, "Invalid prefix mapping: default vocabulary \"%1$s\" must not be re-declared."},
	"OPF-007c": {Error, "Invalid prefix mapping: a prefix to the Dublin Core /elements/1.1/ namespace must not be declared"},
	"OPF-008":  {Suppressed, ""},
	"OPF-009":  {Suppressed, ""},
	"OPF-010":  {Error, "Error resolving reference: \"%1$s\"."},
	"OPF-011":  {Error, "itemref can’t have both page-spread-right and page-spread-left properties."},
	"OPF-012":  {Error, "Item property \"%1$s\" is not defined for media type \"%2$s\"."},
	"OPF-013":  {Warning, "Resource \"%1$s\" is declared with MIME type \"%2$s\" in content, but has MIME type \"%3$s\" in the package document."},
	"OPF-014":  {Error, "The property \"%1$s\" should be declared in the OPF file."},
	"OPF-015":  {Error, "The property \"%1$s\" should not be declared in the OPF file."},
	"OPF-016":  {Error, "The element \"rootfile\" is missing its required attribute \"full-path\"."},
	"OPF-017":  {Error, "The attribute \"full-path\" on element \"rootfile\" must not be empty."},
	"OPF-018":  {Warning, "The \"remote-resources\" property was declared in the Package Document, but no reference to remote resources has been found."},
	"OPF-018b": {Usage, "The \"remote-resources\" property was declared in the Package Document, but no reference to remote resources has been found; please check scripted content to make sure the property is legit. "},
	"OPF-019":  {Suppressed, ""},
	"OPF-020":  {Suppressed, ""},
	"OPF-021":  {Warning, "Use of non-registered URI scheme type in href: \"%1$s\"."},
	"OPF-025":  {Error, "Property value list \"%1$s\" is not allowed, only one value must be specified."},
	"OPF-026":  {Error, "Found malformed property value: \"%1$s\"."},
	"OPF-027":  {Error, "Undefined property: \"%1$s\"."},
	"OPF-028":  {Error, "Undeclared prefix: \"%1$s\"."},
	"OPF-029":  {Error, "The file \"%1$s\" does not appear to match the media type %2$s, as specified in the OPF file."},
	"OPF-030":  {Error, "The unique-identifier \"%1$s\" was not found."},
	"OPF-031":  {Error, "File listed in reference element in guide was not declared in OPF manifest: %1$s."},
	"OPF-032":  {Error, "Guide references \"%1$s\" which is not a valid \"OPS Content Document\"."},
	"OPF-033":  {Error, "The spine contains no linear resources."},
	"OPF-034":  {Error, "The spine contains multiple references to the manifest item with id \"%1$s\"."},
	"OPF-035":  {Warning, "Media type \"text/html\" is not appropriate for XHTML/OPS."},
	"OPF-036":  {Usage, "Video type \"%1$s\" might not be supported by reading systems"},
	"OPF-037":  {Warning, "Found deprecated media-type \"%1$s\"."},
	"OPF-038":  {Warning, "Media type \"%1$s\" is not appropriate for an OEBPS 1.2 context; Use \"text/x-oeb1-document\" instead."},
	"OPF-039":  {Warning, "Media-type \"%1$s\" is not appropriate in an OEBPS 1.2 context. Use \"text/x-oeb1-css\" instead."},
	"OPF-040":  {Error, "Fallback item with id \"%1$s\" could not be found."},
	"OPF-041":  {Error, "Fallback-style item with id \"%1$s\" could not be found."},
	"OPF-042":  {Error, "\"%1$s\" is not a permissible spine media-type."},
	"OPF-043":  {Error, "Spine item with non-standard media-type \"%1$s\" has no fallback."},
	"OPF-044":  {Error, "Spine item with non-standard media-type \"%1$s\" has no EPUB content document fallback."},
	"OPF-045":  {Error, "Encountered circular reference in fallback chain."},
	"OPF-046":  {Suppressed, ""},
	"OPF-047":  {Usage, "OPF file is using OEBPS 1.2 syntax allowing backwards compatibility."},
	"OPF-048":  {Error, "Package tag is missing its required unique-identifier attribute and value."},
	"OPF-049":  {Error, "Item id \"%1$s\" was not found in the manifest."},
	"OPF-050":  {Error, "TOC attribute references resource with non-NCX mime type; \"application/x-dtbncx+xml\" is expected."},
	"OPF-051":  {Suppressed, "Image dimensions exceed recommended size."},
	"OPF-052":  {Error, "Role value \"%1$s\" is not valid."},
	"OPF-053":  {Warning, "Date value \"%1$s\" does not follow recommended syntax as per http://www.w3.org/TR/NOTE-datetime:%2$s."},
	"OPF-054":  {Error, "Date value \"%1$s\" is not valid as per http://www.w3.org/TR/NOTE-datetime:%2$s."},
	"OPF-055":  {Warning, "%1$s tag is empty."},
	"OPF-056":  {Suppressed, ""},
	"OPF-057":  {Suppressed, "Image file length exceeds recommended size."},
	"OPF-058":  {Suppressed, ""},
	"OPF-059":  {Suppressed, ""},
	"OPF-060":  {Error, "Duplicate entry in the ZIP file: \"%1$s\" (file names must be unique after Unicode canonical normalization and full case folding)."},
	"OPF-062":  {Usage, "Found Adobe page-map attribute on spine element in opf file."},
	"OPF-063":  {Warning, "Referenced Adobe page-map item \"%1$s\" was not found in the manifest."},
	"OPF-064":  {Info, "OPF declares type \"%1$s\", validating using profile \"%2$s\"."},
	"OPF-065":  {Error, "Invalid metadata declaration, probably due to a cycle in \"refines\" metadata."},
	"OPF-066":  {Error, "Missing \"dc:source\" or \"source-of\" pagination metadata. The pagination source must be identified using the \"dc:source\" and \"source-of\" properties when the content includes page break markers."},
	"OPF-067":  {Error, "The resource \"%1$s\" must not be listed both as  a \"link\" element in the package metadata and as a manifest item."},
	"OPF-068":  {Suppressed, ""},
	"OPF-069":  {Suppressed, ""},
	"OPF-070":  {Warning, "Custom collection role \"%1$s\" is an invalid URL."},
	"OPF-071":  {Error, "Index collections must only contain resources pointing to XHTML Content Documents."},
	"OPF-072":  {Usage, "Metadata element \"%1$s\" is empty."},
	"OPF-073":  {Error, "External identifiers must not appear in the document type declaration."},
	"OPF-074":  {Error, "Package resource \"%1$s\" is declared in several manifest items."},
	"OPF-075":  {Error, "Preview collections must only point to EPUB Content Documents."},
	"OPF-076":  {Error, "The URI of preview collections link elements must not include EPUB canonical fragment identifiers."},
	"OPF-077":  {Warning, "A Data Navigation Document should not be included in the spine."},
	"OPF-078":  {Error, "An EPUB Dictionary must contain at least one Content Document with dictionary content (epub:type \"dictionary\")."},
	"OPF-079":  {Warning, "Dictionary content was found (epub:type \"dictionary\"), the Package Document should declare the dc:type \"dictionary\"."},
	"OPF-080":  {Warning, "A Search Key Map document file name should have the extension \".xml\"."},
	"OPF-081":  {Error, "Resource \"%1$s\" (referenced from an EPUB Dictionary collection) was not found."},
	"OPF-082":  {Error, "Found an EPUB Dictionary collection containing more than one Search Key Map Document."},
	"OPF-083":  {Error, "Found an EPUB Dictionary collection containing no Search Key Map Document."},
	"OPF-084":  {Error, "Found an EPUB Dictionary collection containing resource \"%1$s\" which is neither a Search Key Map Document nor an XHTML Content Document."},
	"OPF-085":  {Warning, "\"dc:identifier\" value \"%1$s\" is marked as a UUID, but is an invalid UUID."},
	"OPF-086":  {Warning, "Property \"%1$s\" is deprecated. Consider using %2$s instead."},
	"OPF-086b": {Usage, "epub:type value \"%1$s\" is deprecated. Consider using %2$s instead."},
	"OPF-086c": {Warning, "the \"%1$s\" reserved prefix is deprecated."},
	"OPF-087":  {Usage, "epub:type value \"%1$s\" is not allowed on documents of type \"%2$s\"."},
	"OPF-088":  {Usage, "Unrecognized epub:type value \"%1$s\"."},
	"OPF-089":  {Error, "The \"alternate\" link rel keyword cannot be paired with other keywords."},
	"OPF-090":  {Usage, "It is encouraged to use MIME media type \"%1$s\" instead of \"%2$s\"."},
	"OPF-091":  {Error, "The item href URL must not have a fragment identifier."},
	"OPF-092":  {Error, "Language tag \"%1$s\" is not well-formed: %2$s"},
	"OPF-093":  {Error, "The \"media-type\" attribute is required for linked resources located in the EPUB container"},
	"OPF-094":  {Error, "The \"media-type\" attribute is required for \"%1$s\" links."},
	"OPF-095":  {Error, "The \"media-type\" attribute of \"voicing\" links must be an audio MIME type, but found \"%1$s\"."},
	"OPF-096":  {Error, "Non-linear content must be reachable, but found no hyperlink to \"%1$s\"."},
	"OPF-096b": {Usage, "No hyperlink was found to non-linear document \"%1$s\", please check that it can be reached from scripted content."},
	"OPF-097":  {Usage, "Resource \"%1$s\" is listed in the manifest, but no reference to it was found in content documents."},
	"OPF-098":  {Error, "The \"href\" attribute must reference resources, not elements in the package document, but found URL \"%1$s\"."},
	"OPF-099":  {Error, "The manifest must not list the package document."},
	"OPF-100":  {Usage, "The \"%1$s\" property only applies to pre-paginated content."},
	"PKG-001":  {Warning, "Validating the EPUB against version %1$s but detected version %2$s."},
	"PKG-003":  {Error, "Unable to read EPUB file header.  This is likely a corrupted EPUB file."},
	"PKG-004":  {Fatal, "Corrupted EPUB ZIP header."},
	"PKG-005":  {Error, "The mimetype file has an extra field of length %1$s. The use of the extra field feature of the ZIP format is not permitted for the mimetype file."},
	"PKG-006":  {Error, "Mimetype file entry is missing or is not the first file in the archive."},
	"PKG-007":  {Error, "The content of the mimetype file must be the string \"application/epub+zip\"%1$s"},
	"PKG-008":  {Fatal, "Unable to read file \"%1$s\"."},
	"PKG-009":  {Error, "The file name \"%1$s\" contains characters that are not allowed in OCF file names: %2$s."},
	"PKG-010":  {Warning, "The file name \"%1$s\" contains spaces, which may create interoperability issues with older reading systems."},
	"PKG-011":  {Error, "The file name \"%1$s\" is not allowed to end with \".\"."},
	"PKG-012":  {Usage, "The file name \"%1$s\" contains non-ASCII characters, which might create interoperability issues with older reading systems."},
	"PKG-013":  {Error, "The EPUB file includes multiple OPS renditions."},
	"PKG-014":  {Warning, "The EPUB contains empty directory \"%1$s\"."},
	"PKG-015":  {Fatal, "Unable to read EPUB contents: %1$s"},
	"PKG-016":  {Warning, "Use only lowercase characters for the EPUB file extension for maximum compatibility."},
	"PKG-017":  {Warning, "Uncommon EPUB file extension."},
	"PKG-018":  {Fatal, "The EPUB file could not be found."},
	"PKG-020":  {Error, "OPF file \"%1$s\" could not be found."},
	"PKG-021":  {Error, "Corrupted image file encountered."},
	"PKG-022":  {Warning, "Wrong file extension for image. The image is a \"%1$s\" file but has the file extension \"%2$s\"."},
	"PKG-023":  {Usage, "Validating the EPUB against version 2.0, default validation profile will be used."},
	"PKG-024":  {Usage, "Uncommon EPUB file extension."},
	"PKG-025":  {Error, "Publication resource must not be located in the META-INF directory"},
	"PKG-026":  {Error, "Obfuscated resource must be a Font Core Media Type (was declared as \"%1$s\" in \"%2$s\")."},
	"PKG-027":  {Fatal, "Could not extract EPUB ZIP content, probably due to file names not encoded in UTF-8.  "},
	"RSC-001":  {Error, "File \"%1$s\" could not be found."},
	"RSC-002":  {Fatal, "Required META-INF/container.xml resource could not be found."},
	"RSC-003":  {Error, "No rootfile tag with media type \"application/oebps-package+xml\" was found in the container."},
	"RSC-004":  {Info, "File \"%1$s\" is encrypted, its content will not be checked."},
	"RSC-005":  {Error, "Error while parsing file: %1$s"},
	"RSC-006":  {Error, "Remote resource reference is not allowed in this context; resource \"%1$s\" must be located in the EPUB container."},
	"RSC-006b": {Usage, "Resource \"%1$s\" is located outside the EPUB Container; please check the resource is retrieved in scripted content. "},
	"RSC-007":  {Error, "Referenced resource \"%1$s\" could not be found in the EPUB."},
	"RSC-007w": {Warning, "Referenced resource \"%1$s\" could not be found in the EPUB."},
	"RSC-008":  {Error, "Referenced resource \"%1$s\" is not declared in the OPF manifest."},
	"RSC-009":  {Warning, "A non-SVG image resource should not be defined with a fragment identifier."},
	"RSC-010":  {Error, "Reference to non-standard resource type found."},
	"RSC-011":  {Error, "Found a reference to a resource that is not a spine item."},
	"RSC-012":  {Error, "Fragment identifier is not defined."},
	"RSC-013":  {Usage, "Fragment identifier is used in a reference to a stylesheet resource."},
	"RSC-014":  {Usage, "Fragment identifier defines an incompatible resource type."},
	"RSC-015":  {Usage, "A fragment identifier is required for svg use tag references."},
	"RSC-016":  {Fatal, "Fatal Error while parsing file: %1$s"},
	"RSC-017":  {Warning, "Warning while parsing file: %1$s"},
	"RSC-018":  {Suppressed, ""},
	"RSC-019":  {Warning, "EPUBs with Multiple Renditions should contain a META-INF/metadata.xml file."},
	"RSC-020":  {Error, "\"%1$s\" is not a valid URL (%2$s)"},
	"RSC-021":  {Error, "A Search Key Map Document must point to Content Documents (\"%1$s\" was not found in the spine)."},
	"RSC-022":  {Info, "Cannot check image details (requires Java version 7 or higher)."},
	"RSC-023":  {Suppressed, ""},
	"RSC-024":  {Usage, "Informative parsing warning: %1$s"},
	"RSC-025":  {Usage, "Informative parsing error: %1$s"},
	"RSC-026":  {Error, "URL \"%1$s\" leaks outside the container (it is not a valid-relative-ocf-URL-with-fragment string)"},
	"RSC-027":  {Warning, "XML document is encoded in UTF-16. It should be encoded in UTF-8 instead."},
	"RSC-028":  {Error, "XML documents must be encoded in UTF-8, but %1$s was detected."},
	"RSC-029":  {Error, "Data URL is not allowed in this context."},
	"RSC-030":  {Error, "File URLs are not allowed in EPUB, but found \"%1$s\"."},
	"RSC-031":  {Warning, "Remote resource references should use HTTPS, but found \"%1$s\"."},
	"RSC-032":  {Error, "Fallback must be provided for foreign resources, but found none for resource \"%1$s\" of type \"%2$s\"."},
	"RSC-033":  {Error, "Relative URL strings must not have a query component, but found one in \"%1$s\"."},
	"RSC-034":  {Error, "Scripts must have a JavaScript media type."},
	"RSC-035":  {Usage, "\"%1$s\" is a legacy media type for JavaScript. Consider using 'text/javascript' instead."},
	"RSC-036":  {Usage, "%1$s"},
	"SCP-001":  {Suppressed, ""},
	"SCP-002":  {Suppressed, ""},
	"SCP-003":  {Suppressed, ""},
	"SCP-004":  {Suppressed, ""},
	"SCP-005":  {Suppressed, ""},
	"SCP-006":  {Suppressed, ""},
	"SCP-007":  {Suppressed, ""},
	"SCP-008":  {Suppressed, ""},
	"SCP-009":  {Suppressed, ""},
	"SCP-010":  {Suppressed, ""},
}
